title: Andrea Sanchietti's Homepage
page-top-title: Andrea Sanchietti
top-section-bg-text: Andrea Sanchietti
home-subtitle: 
copyright-text: '&copy; Andrea Sanchietti 2024-2025. All Rights Reserved.'
